FROM node:18-bullseye-slim

RUN npm i -g pnpm

USER node

WORKDIR /home/node/logstore

COPY --chown=node:node ./package.json ./
COPY --chown=node:node ./pnpm-lock.yaml ./
COPY --chown=node:node ./pnpm-workspace.yaml ./
COPY --chown=node:node ./tsconfig.node.json ./
COPY --chown=node:node ./turbo.json ./

COPY --chown=node:node ./packages/contracts/package.json ./packages/contracts/
COPY --chown=node:node ./packages/protocol/package.json ./packages/protocol/

RUN pnpm install

COPY --chown=node:node ./packages/contracts/ ./packages/contracts/
COPY --chown=node:node ./packages/protocol/ ./packages/protocol/

RUN cp ./packages/contracts/.env.dev-network ./packages/contracts/.env

RUN pnpm build

WORKDIR /home/node/logstore/packages/contracts

CMD npx hardhat run ./scripts/0_deployNodeManager.ts --network streamr-dev-docker
