FROM golang:1.20.4-bullseye

RUN useradd -ms /bin/bash kyve

RUN curl https://get.ignite.com/cli! | bash

USER kyve
WORKDIR /home/kyve

RUN git clone https://github.com/KYVENetwork/chain.git chain && cd chain && git checkout v1.2.0

WORKDIR /home/kyve/chain

COPY ./assets/kyve/config.yml ./config.yml

CMD [ "ignite", "chain", "serve" ,"--skip-proto", "-v" ]
