FROM logstore-base

WORKDIR /home/node/storage-proxy

COPY --chown=node:node ./modules/logstore-node/packages/storage-proxy/package.json ./

RUN pnpm install

COPY --chown=node:node ./ ./

RUN pnpm build

WORKDIR /home/node

USER root
RUN mkdir /firstrun && chown node:node /firstrun
RUN npm i -g /home/node/logstore/packages/cli
RUN npm i -g /home/node/storage-proxy

USER node

CMD [ "start-in-docker" ]
