FROM node:16-buster

# RUN apk add libsecret-dev
RUN apt update
RUN apt install -y libsecret-1-dev
RUN mkdir /firstrun && chown node:node /firstrun
RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

WORKDIR /home/node/app

RUN npm i -g pnpm

USER node

COPY --chown=node:node ./package.json ./package.json
COPY --chown=node:node ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY --chown=node:node ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY --chown=node:node ./packages/contracts/package.json ./packages/contracts/package.json

RUN pnpm install

COPY --chown=node:node ./packages/contracts ./packages/contracts

WORKDIR /home/node/app/packages/contracts
RUN pnpm install

RUN cp .env.dev-network .env

RUN chmod +x start.sh
ENTRYPOINT [ "sh", "./start.sh" ]
